/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/translate-image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Translate Image
         * @description Preserve M0 mock requests and execute the M1 real pipeline for auto-language requests.
         */
        post: operations["translate_image_v1_translate_image_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** ImageSource */
        ImageSource: {
            /** Client Image Id */
            client_image_id: string;
            /** Rendered Height */
            rendered_height: number;
            /** Rendered Width */
            rendered_width: number;
            /**
             * Source
             * Format: uri
             */
            source: string;
            /**
             * Source Kind
             * @constant
             */
            source_kind: "url";
        };
        /** TranslationImageRequest */
        TranslationImageRequest: {
            image: components["schemas"]["ImageSource"];
            /**
             * Page Url
             * Format: uri
             */
            page_url: string;
            /**
             * Reading Order
             * @enum {string}
             */
            reading_order: "auto" | "ltr" | "rtl";
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /**
             * Source Language
             * @enum {string}
             */
            source_language: "auto" | "ja" | "ko" | "en";
            /**
             * Target Language
             * @constant
             */
            target_language: "zh-Hant";
        };
        /** TranslationImageResponse */
        TranslationImageResponse: {
            /** Client Image Id */
            client_image_id: string;
            /** Image Height */
            image_height: number;
            /** Image Id */
            image_id: string;
            /** Image Width */
            image_width: number;
            /** Regions */
            regions: components["schemas"]["TranslationRegion"][];
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /** Warnings */
            warnings: string[];
        };
        /** TranslationRegion */
        TranslationRegion: {
            /** Detection Confidence */
            detection_confidence: number;
            /**
             * Orientation
             * @enum {string}
             */
            orientation: "vertical" | "horizontal";
            /** Polygon */
            polygon: [
                number,
                number
            ][];
            /** Recognition Confidence */
            recognition_confidence: number;
            /** Region Id */
            region_id: string;
            /** Source Text */
            source_text: string;
            /** Translated Text */
            translated_text: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    translate_image_v1_translate_image_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranslationImageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranslationImageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
